with-expecter: true
packages:
  github.com/chickey/blog/internal/handlers:
    config:
      filename: "{{.InterfaceName | snakecase}}.go"
      dir: "{{.InterfaceDir}}/mock"
      mockname: "{{.InterfaceName | camelcase | firstUpper}}"
      outpkg: "mock"
      inpackage: false
    interfaces:
      userReader:
      usersLister:
      userCreator:
      userDeleter:
      userUpdater:
      blogReader:
      blogsLister:
      blogCreator:
      blogDeleter:
      blogUpdater:
      commentsLister:
      commentCreator:
      commentDeleter:
      commentUpdater: