// Code generated by mockery v2.51.1. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/chickey/blog/internal/models"
)

// BlogReader is an autogenerated mock type for the blogReader type
type BlogReader struct {
	mock.Mock
}

type BlogReader_Expecter struct {
	mock *mock.Mock
}

func (_m *BlogReader) EXPECT() *BlogReader_Expecter {
	return &BlogReader_Expecter{mock: &_m.Mock}
}

// ReadBlog provides a mock function with given fields: ctx, id
func (_m *BlogReader) ReadBlog(ctx context.Context, id uint64) (models.Blog, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ReadBlog")
	}

	var r0 models.Blog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (models.Blog, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) models.Blog); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Blog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlogReader_ReadBlog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadBlog'
type BlogReader_ReadBlog_Call struct {
	*mock.Call
}

// ReadBlog is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *BlogReader_Expecter) ReadBlog(ctx interface{}, id interface{}) *BlogReader_ReadBlog_Call {
	return &BlogReader_ReadBlog_Call{Call: _e.mock.On("ReadBlog", ctx, id)}
}

func (_c *BlogReader_ReadBlog_Call) Run(run func(ctx context.Context, id uint64)) *BlogReader_ReadBlog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *BlogReader_ReadBlog_Call) Return(_a0 models.Blog, _a1 error) *BlogReader_ReadBlog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlogReader_ReadBlog_Call) RunAndReturn(run func(context.Context, uint64) (models.Blog, error)) *BlogReader_ReadBlog_Call {
	_c.Call.Return(run)
	return _c
}

// NewBlogReader creates a new instance of BlogReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlogReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlogReader {
	mock := &BlogReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
