// Code generated by mockery v2.51.1. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BlogDeleter is an autogenerated mock type for the blogDeleter type
type BlogDeleter struct {
	mock.Mock
}

type BlogDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *BlogDeleter) EXPECT() *BlogDeleter_Expecter {
	return &BlogDeleter_Expecter{mock: &_m.Mock}
}

// DeleteBlog provides a mock function with given fields: ctx, id
func (_m *BlogDeleter) DeleteBlog(ctx context.Context, id uint64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BlogDeleter_DeleteBlog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlog'
type BlogDeleter_DeleteBlog_Call struct {
	*mock.Call
}

// DeleteBlog is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *BlogDeleter_Expecter) DeleteBlog(ctx interface{}, id interface{}) *BlogDeleter_DeleteBlog_Call {
	return &BlogDeleter_DeleteBlog_Call{Call: _e.mock.On("DeleteBlog", ctx, id)}
}

func (_c *BlogDeleter_DeleteBlog_Call) Run(run func(ctx context.Context, id uint64)) *BlogDeleter_DeleteBlog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *BlogDeleter_DeleteBlog_Call) Return(_a0 error) *BlogDeleter_DeleteBlog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BlogDeleter_DeleteBlog_Call) RunAndReturn(run func(context.Context, uint64) error) *BlogDeleter_DeleteBlog_Call {
	_c.Call.Return(run)
	return _c
}

// NewBlogDeleter creates a new instance of BlogDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlogDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlogDeleter {
	mock := &BlogDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
